class State < ApplicationRecord
  validates_presence_of :st_name
  validates_presence_of :st_abbrev

  STATE_NAME_TO_ABBR = {
    'Alabama' => 'AL',
    'Alaska' => 'AK',
    'America_Samoa' => 'AS',
    'Arizona' => 'AZ',
    'Arkansas' => 'AR',
    'California' => 'CA',
    'Colorado' => 'CO',
    'Connecticut' => 'CT',
    'Delaware' => 'DE',
    'District_of_Columbia' => 'DC',
    'Federated_States_of_Micronesia' => 'FM',
    'Florida' => 'FL',
    'Georgia' => 'GA',
    'Guam' => 'GU',
    'Hawaii' => 'HI',
    'Idaho' => 'ID',
    'Illinois' => 'IL',
    'Indiana' => 'IN',
    'Iowa' => 'IA',
    'Kansas' => 'KS',
    'Kentucky' => 'KY',
    'Louisiana' => 'LA',
    'Maine' => 'ME',
    'Maryland' => 'MD',
    'Massachusetts' => 'MA',
    'Marshall_Islands' => 'MH',
    'Michigan' => 'MI',
    'Minnesota' => 'MN',
    'Mississippi' => 'MS',
    'Missouri' => 'MO',
    'Montana' => 'MT',
    'Nebraska' => 'NE',
    'Nevada' => 'NV',
    'New_Hampshire' => 'NH',
    'New_Jersey' => 'NJ',
    'New_Mexico' => 'NM',
    'New_York' => 'NY',
    'North_Carolina' => 'NC',
    'North_Dakota' => 'ND',
    'Northern_Mariana_Islands' => 'MP',
    'Ohio' => 'OH',
    'Oklahoma' => 'OK',
    'Oregon' => 'OR',
    'Palau' => 'PW',
    'Pennsylvania' => 'PA',
    'Puerto_Rico' => 'PR',
    'Rhode_Island' => 'RI',
    'South_Carolina' => 'SC',
    'South_Dakota' => 'SD',
    'Tennessee' => 'TN',
    'Texas' => 'TX',
    'Utah' => 'UT',
    'Vermont' => 'VT',
    'Virgin_Island' => 'VI',
    'Virginia' => 'VA',
    'Washington' => 'WA',
    'West_Virginia' => 'WV',
    'Wisconsin' => 'WI',
    'Wyoming' => 'WY'
  }

  def self.find_state_abbreviation(st_name)
    STATE_NAME_TO_ABBR[st_name]
  end

end
